### ISSUE TITLE
Create 1.0 Release

### ISSUE THREAD

**Issue by jkeen** [jkeen/tracking_number_data#10]
I think after #8 and #9 are merged in, we should create a `1.0.0` release, tag it as such, and then from that point forward release updates in the semver format where patches are bug fixes to existing logic, minor releases are additions of new tracking number types or additional information that _might_ require clients to be modified slightly, and a major release would be something so significant it's sure to cause compatibility problems for clients (let's not do that for a long time).

Then the clients can pin themselves to a version tag. 

I'm pretty close to releasing the new `tracking_number` which supports this library.

Sound good to you @adgaudio?

**Comment by adgaudio** [comment]
Hi!  Yes, this sounds great!  Let me know if or when I should test anything and integrate into the java branch.  Sorry I've been totally MIA for a little bit.  I guess we come and go in waves on the project :)

FYI -  I might build a c++ library for this in the near future.  A company I contribute to has an android app and soon will have an iOS app using this code.

**Comment by jkeen** [comment]
Great! Yeah sorry I was MIA for the end of last year. Waves indeed. 🌊 

I think it's all set for 1.0 after those two PRs get merged in. I want to add some more tests to check specific formatting within those files too but I can do that later. It's at least checking formatting automatically now.

One thing we should discuss is the state of the `dev` branch, because I think we might want to reset it to master after 1.0 and use it as the test/integration branch. Currently there are some Lasership commits in there that you said weren't quite ready for PR? Do you have a local branch for the lasership work?

Cool re: the c++ version!

**Comment by adgaudio** [comment]
I just rebased the dev branch and looks like outstanding differences are a "container Type" in fedex.json, addition of lasership.json, and hong kong post in s10.json.  going to update dev to that commit.
