### ISSUE TITLE
Better detect multiple shipper packages

### ISSUE THREAD

**Issue by jkeen** [jkeen/tracking_number_data#12]
Originally documented in [this issue on `tracking_number`](https://github.com/jkeen/tracking_number/issues/27), a tracking number `9274890103422546330271` was labeled as [FedExSmartPost, USPS91] but it was actually shipped with UPS and delivered via USPS.

Another tracking number `9261290172376608200214` was labeled as [FedExSmartPost, USPS91] but it was actually shipped with OSM, delivered via USPS.

Reason this is needed: needed to query the correct shipper's website.

**Findings so far:**
I think it has something to do with the SCNC portion of the tracking number.

This [document]( http://images.fedex.com/us/solutions/ppe/FedEx_Ground_Label_Layout_Specification.pdf) says SCNC 11, 12, and 13 identify a Fedex ground tracking number, and the two numbers @vimagick specified 

From the other tracking numbers I've been able to find in my email it seems like a pretty good bet that SCNC=74 means sent by UPS, but a variety of other numbers that are not OSM have SCNC=61, so not sure exactly what that one means and can't seem to find a list to look these up in.

A UPS SurePost number, however,  looks like a UPS number but has `YW` for the ServiceType, even though it's delivered by USPS.

**Comment by jkeen** [comment]
_From @adgaudio on July 11, 2017 0:26_

After looking at your examples, it looks like multiple US courier services may have some standard or agreement with USPS to send mail, and they all use this type of tracking number.  If anyone can find documentation revealing more about the nature of the agreement, this would be helpful.  

The (slightly modified) SmartPost regular expression we have that does match both of these tracking numbers is the following:

      "regex": [
        "(?P<ApplicationIdentifier>92)?",
        "(?P<SerialNumber>",
        "(?P<SCNC>[0-9]{2})",
        "(?P<ClassOfService>[0-9]{3})",
        "(?P<ShipperId>[0-9]{7})",
        "(?P<PackageId>[0-9]{7})",
        ")",
        "(?P<CheckDigit>[0-9])"
      ],

Presumably, the shipperId in this regular expression will identify the origin shipper.  Therefore, we might want to always associate tracking numbers matching this regular expression with USPS.  Secondarily, we can use the shipperId to identify the package as a FedEx, UPS or OSM package.

So we need a mapping of shipper ids.  Assuming the regex above is valid, then:
1723766 --> OSM shipper id
1034225 --> UPS shipper id


Extra reading for reference:
- USPS Parcel Select https://about.usps.com/postal-bulletin/2007/html/pb22219/kit2_002.html
- Fedex SmartPost
  - http://www.fedex.com/us/smart-post/network.html#tab2
  - http://www.fedex.com/us/smart-post/network.html#tab1
- UPS SurePost
https://www.ups.com/worldshiphelp/WS14/ENU/AppHelp/SHIPMENT/About_UPS_SurePost.htm


Side note:  The regular expression above came from https://github.com/jkeen/tracking_number_data/pull/1 which is a refactor of the tracking number library to make it cross-language compatible.

**Comment by jkeen** [comment]
_From @adgaudio on July 19, 2017 19:47_

Ok - I started basic support for this in  jkeen/tracking_number_data#1

I didn't create an "additional" field with the shipper ids because I don't have enough labels  yet to verify who the shipper_ids belong to.  We should create that additional field in a second pr to jkeen/tracking_number_data.  

When this library incorporates both PRs, we can close this ticket.

**Comment by jkeen** [comment]
I think `ShipperId` is actually the company that shipped it, not the courier, and `SCNC` is the field we want to look into.

PR https://github.com/jkeen/tracking_number/pull/28, which integrates the jkeen/tracking_number_data#1 work identifies these numbers as USPS now.

This [document]( http://images.fedex.com/us/solutions/ppe/FedEx_Ground_Label_Layout_Specification.pdf) says SCNC 11, 12, and 13 identify a Fedex ground tracking number, and the two numbers @vimagick specified have SCNC 74 and 61, respectively, which might indicate UPS and OSM?

**Comment by jkeen** [comment]
@vimagick Can you clarify for me what you're trying to identify exactly and why? Understanding the motivation would help with designing these changes

**Comment by jkeen** [comment]
From the other tracking numbers I've been able to find in my email it seems like a pretty good bet that SCNC=74 means sent by UPS, but a variety of other numbers that are not OSM have SCNC=61, so not sure exactly what that one means and can't seem to find a list to look these up in.

A UPS SurePost number, however,  looks like a UPS number but has `YW` for the ServiceType, even though it's delivered by USPS.

**Comment by jkeen** [comment]
_From @vimagick on August 4, 2017 23:40_

@jkeen I need to query the tracking number on carrier's website to get logistics progresses.

**Comment by devkir** [comment]
Packages shipped by Fedex SmartPost and delivered by USPS always have SCNC 61 and Service type 29 on scanned USPS tracking number.
Tested by 20+ trackings I have in production database

**Comment by jkeen** [comment]
🎉
