### ISSUE TITLE
Unmatched Amazon logistics tracking number

### ISSUE THREAD

**Issue by Phyks** [jkeen/tracking_number_data#16]
Hi,

I have some Amazon logistics tracking numbers which seems to not be matched by the regexes from this repo. I am in Europe (Paris), so not sure if this is different here or not.

I don't have many of them to confirm, but all of them I have so far are made of the letter C followed by 11 digits. Are you familiar with such tracking numbers?

Thanks!

**Comment by jkeen** [comment]
I haven't seen any like that before, but if you can find some documentation on them we can see about adding them

**Comment by Phyks** [comment]
I did not find much details about it so far. I came across this repo https://github.com/repat/shipping-service-providers-check/blob/master/src/ShippingServiceProvidersCheck/default_providers.php which defines them as AF + 10 digits for Germany. So I guess these numbers are country dependant and for France it should be something like C + 11 digits. TBA + 12 digits should be only for US I think. 

Still, I only have 3 of them so far, so it's not very representative.

**Comment by Phyks** [comment]
By digging in all of my emails, I found 14 of them actually. All of them matches
```
C[12AE]00[0-9]{7}3
```
so far.

Still not sure about the exact structure though :/ The trailing 3 and the second character being either 1, 2, A or E (or anything else not appearing in my subset) is a bit weird.

**Comment by jkeen** [comment]
Well that's a start! The Amazon ones are a bit of a mystery still, and it
sucks that they don't seem to have a check digit (which would help
eliminating numbers that look like tracking numbers but aren't)

**Comment by jkeen** [comment]
I added a pretty generic implementation of this, more inline with that other repo's strategy you linked @Phyks 

Thanks for the research
