### ISSUE TITLE
ontrac tracking number not detected

### ISSUE THREAD

**Issue by martinipsy** [jkeen/tracking_number_data#17]
Hey! Congralations for this great gem, you did an awesome job!

I found an ontrac tracking number that is not detected by the gem:
`D10011326755777`

I've tested others starting with `D` and they don't work either.
what do you think?

**Comment by jkeen** [comment]
Looks like the have a new tracking number type. Do you have other examples of the `D` numbers so I can add a new type?

**Comment by martinipsy** [comment]
Sure!
`D10011354453707`
`D10011345983010`
`D10011342332145`

**Comment by kktsvetkov** [comment]
I've looked for regex patterns for OnTrac and it seems that only the first character is either C or D:
https://www.trackingmore.com/tracking-status-detail-en-253.html

**Comment by jkeen** [comment]
Started PR #61 to try and take a crack at the check digit algorithm. FWIW the test suite now will now actually run through all the example numbers and algorithms, so if anyone wants to take a crack at changing that JSON until the tests pass, feel free

**Comment by jkeen** [comment]
Figured it out
