### ISSUE TITLE
DHL Ecommerce not supported

### ISSUE THREAD

**Issue by octave** [jkeen/tracking_number_data#19]
Hi guys,

Great gem! We found out that the new DHL ecommerce format isn't supported, example:

- GM2951173225174494
- GM295117494011169042

It seems like they all start with GM (in our case) but apparently they can have different starts: http://parcelsapp.com/en/carriers/dhl-ecommerce

**Comment by LagTag** [comment]
We have a lot of GM tracking numbers, but I haven't been able to find a valid pattern besides the GM.

**Comment by jkeen** [comment]
Found some more info on these numbers and added the definition
