### ISSUE TITLE
Amazon Logistics

### ISSUE THREAD

**Issue by adgaudio** [jkeen/tracking_number_data#2]
@jkeen 

I was looking at some Amazon Logistics tracking numbers but don't have access to the "my orders" page on Amazon.  Do you have any idea which one is the tracking number, and how should we parse them?

I scanned the barcodes on an Amazon Logistics package label and found these:

>    big barcode towards top of label: 
> **SNDI9xDHq4_001_v**

>    2D barcode on right side of label:
> **{"cids": {"pkey": "170628125122107217782010201AZ"}}**

>    2D barcode on left side of label:
> **TBA333656997000**
   
 >   Barcode at bottom of label.  The barcode's contents are written underneath the label, and centered-aligned under the barcode. 
> **TBA333656997000**
    
>   I also see the text written between the big barcode and left 2d barcode:
>   **DNI9xDHq4/q/second/1 of 1/9178604518/115**

I think the TBA number is the correct one, but haven't figured out its check sum yet.  Thoughts?  I'd very much like to add support for this, as we have thousands of these packages.

**Comment by jkeen** [comment]
I can't seem to find anything about those numbers either, besides: 

- Amazon Logistics tracking numbers start with TBA
- Amazon these mainly same-day deliveries that are in the same city as the warehouse.

But nothing on check digits, no way to externally track them, and no documentation I've found yet on other information encoded into that number. 

I searched through my amazon account and found two AMZL tracking numbers, through: `TBA343419108000` and `TBA385062830000`. Seems like they all start with `TBA` and end with `000`? Is that what you're seeing from the data you have?

I was trying to use that middle bit as the serial number, running it through some check digit algorithms but no luck yet.

**Comment by adgaudio** [comment]
Hello!  I have acquired a dataset of these TBA numbers, and it looks like they are probably incrementing over time.  I'm going to submit a PR here to support TBA numbers with no check digit algorithm, since it seems likely that TBA numbers might not use one.  TBA is fairy unique, so I think we'll be alright there.

PR coming either tomorrow or next week, depending on when I can get to it.

**Comment by adgaudio** [comment]
Addressed in #3
