### ISSUE TITLE
S10 invalid number is actually valid

### ISSUE THREAD

**Issue by jespern** [jkeen/tracking_number_data#22]
I'm writing a Python version of tracking_number that uses these JSON files, but I found that the "invalid" S10 tracking number on line 29 of s10.json is actually valid. The number is RB123456785XX.

Using the function 'validates_s10?' lifted directly from the original Ruby implementation, it agrees: the number is correct and the checksum passes.

**Comment by jkeen** [comment]
Checksum of the number might be valid, but `XX` isn't a valid courier code and that's part of the validation as described in that file here:

https://github.com/jkeen/tracking_number_data/blob/9b51abb02bc0089de945389481b6cfe80a0e9327/couriers/s10.json#L7-L16

**Comment by jkeen** [comment]
Turns out that wasn't documented very well, but validation can specify some additional checks besides the checksum. This is currently implemented in the ruby version of `tracking_number`

**Comment by jespern** [comment]
Ah, I see, missed that detail. I'll attempt to incorporate that into my Python version as well. Thanks.
