### ISSUE TITLE
Carrier is not detected for some UPS tracking numbers

### ISSUE THREAD

**Issue by shkrt** [jkeen/tracking_number_data#26]
There are UPS tracking numbers that look like this `K1506235620`.

Expected behaviour:
```ruby
TrackingNumber.new('K1506235620').carrier
=> :ups
```

Actual behaviour:
```ruby
TrackingNumber.new('K1506235620').carrier
=> :unknown
```

version used: `1.0.5`

**Comment by jkeen** [comment]
I don't have any record of UPS numbers besides the ones starting with `1Z`. You're sure this is a tracking number and not some other number on the label?

**Comment by shkrt** [comment]
I got that number from one of my customers, and package is actually trackable using it, as seen on the attached image:

![image](https://user-images.githubusercontent.com/10468452/55580070-65cdc700-5722-11e9-8c15-bb808eb4e143.png)



(I intentionally painted out some info for the sake of privacy). But I also don't see that kind of numbers anywhere in the documentation.

Also, [this code](https://github.com/travishaynes/trackerific/blob/a943a21aa7ff29ae608762031c56240a68d9373d/lib/trackerific/services/ups.rb#L8) gives us a clue that there is also UPS tracking numbers starting with `H`

**Comment by shkrt** [comment]
https://www.ups.com/us/en/tracking/help/tracking/tnh.page

**Comment by tleish** [comment]
It appears the code comes from a UPS handwritten labels, also called a UPS Worldwide Services Waybill.  I've seen several posts where it can start with A, H, J, or K.

See:
- https://www.reddit.com/r/UPS/comments/ae8rju/ups_tracking_number_begins_with_k/
- https://www.reddit.com/r/UPS/comments/50wt6p/what_exactly_is_a_handwritten_ups_label/
- http://i.imgur.com/dBiOGiz.jpg
- https://stackoverflow.com/questions/619977/regular-expression-patterns-for-tracking-numbers
    ```
    UPS:
    K2479825491         (UPS ground)
    J4603636537         (UPS next day express)
    1Z87585E4391018698  (regular)
    ```

**Comment by jkeen** [comment]
Added support for these numbers in #59

**Comment by AdamAld** [comment]
Added additional support for UPS WorldWide Express Saver ("V"+10 digits) in #75

**Comment by digital-marketing-engineer** [comment]
We need to have UPS documentation reference of their format.

**Comment by jkeen** [comment]
> We need to have UPS documentation reference of their format.

I'm not sure what you're asking here?
