### ISSUE TITLE
UPS "CheckDigit" in "regex"

### ISSUE THREAD

**Issue by kktsvetkov** [jkeen/tracking_number_data#27]
Hi @jkeen , currently the "CheckDigit" regex part in [couriers/ups.json](https://github.com/jkeen/tracking_number_data/blob/332cd0105/couriers/ups.json#L12) is 

`"(?<CheckDigit>[A-Z0-9]\\s*)"`

but it is meant to be always a digit, so perhaps it can be made more restrictive as only digits, like this ?

`"(?<CheckDigit>[0-9]\\s*)"`

**Comment by jkeen** [comment]
Thanks @kktsvetkov!
