### ISSUE TITLE
Ontrac Checksum

### ISSUE THREAD

**Issue by kktsvetkov** [jkeen/tracking_number_data#28]
Hi, I've found a real OnTrac number, https://www.ontrac.com/trackingres.asp?tracking_number=C12340740337674

![image](https://user-images.githubusercontent.com/694812/65936564-b1d59c00-e425-11e9-8af5-481d0ab6f9a5.png)

I tried the mod10 with 1,2 multipliers and the 4 prefix, but it doesn't seem to work

**Comment by kktsvetkov** [comment]
You can find other numbers to test in GutHub: there are projects with some real data dumps. Here is one: https://github.com/liccoCode/elcuk3/blob/72829c8da81e74b214d143b9fb9349aaf487aaf6/core/test/html/10833010723.csv
```
ONTRAC	C11121553156000
ONTRAC	C11121552953069
ONTRAC	C11121552829468
...
```

**Comment by jkeen** [comment]
@kktsvetkov super quick reply here, but thanks so much for that data dump link! That is going to be a great resource. I added the three numbers you listed to the test cases
