### ISSUE TITLE
Fedex Tracking Number is Identified Incorrectly as DHL

### ISSUE THREAD

**Issue by mandemeskel** [jkeen/tracking_number_data#29]
Hi, the gem is identifying this [valid](https://www.fedex.com/apps/fedextrack/?tracknumbers=5096672442) FedEx tracking number `5096672442` as DHL. FedEx does generate 10 digit tracking numbers just like DHL. I don't quite know how to distinguish the two without making a call to the FedEx API. Nonetheless, it seems the DHL and FedEx JSON files should be updated?

![image](https://user-images.githubusercontent.com/1797701/72566423-a1c4b980-3868-11ea-97f3-695d0d02f568.png)

Thanks for this great gem btw!

**Comment by jkeen** [comment]
I have searched and searched for docs on these 10 digit fedex numbers and even searched through years of emails looking for examples, and I seem to be able to find loads of the ones already in this repo, but no 10 digit ones. 🤷‍♂️

If you've got other examples of this incorrect detection, please open this issue back up! I'd love to solve this if given enough evidence
