### ISSUE TITLE
34 digit fedex express barcodes can begin with 101 or 102.

### ISSUE THREAD

**Issue by akowald** [jkeen/tracking_number_data#51]
Came across a few of the 34 digit fedex barcodes that begin with 101 and 102. Having a look at the regexs, it appears that they must start with 100 to be accepted, is this correct?

https://github.com/jkeen/tracking_number_data/blob/5212dd1f988d0a0a8eb3f26e2b024afd3bf5bc1c/couriers/fedex.json#L46

Here is one: 1027590111820004833500785458233610
I've found 101 and 102, not sure if there are more. Would you accept a PR to accept 10[0-9] ?

**Comment by jkeen** [comment]
I made that change, thanks for the report/sorry for the delay!
