### ISSUE TITLE
Canada Post tracking numbers reporting as invalid

### ISSUE THREAD

**Issue by alexabbott** [jkeen/tracking_number_data#55]
Canada Post uses tracking numbers that are 16 numeric digits (ex `0073938000549297`) -- this tracking gem reports this as an invalid tracking number, which is incorrect.

**Comment by jkeen** [comment]
@alexabbott I took a crack at this finally, and got things working but need some more numbers to plug in for testing/verification. Do you have a few?

**Comment by jkeen** [comment]
Found some—merged
