### ISSUE TITLE
Dead FedEx links

### ISSUE THREAD

**Issue by BakeryD** [jkeen/tracking_number_data#80]
Super nit pick, but lots of the fed ex links are dead.
I was able to find this one on web.archive.org and will update this with any additional ones I find.

~http://images.fedex.com/us/solutions/ppe/FedEx_Ground_Label_Layout_Specification.pdf~ => https://web.archive.org/web/20211007110607/http://images.fedex.com/us/solutions/ppe/FedEx_Ground_Label_Layout_Specification.pdf

**Comment by jkeen** [comment]
Thanks, I added them to the wiki and will update the readme to reflect that

https://github.com/jkeen/tracking_number_data/wiki/Reference-Documents
