### ISSUE TITLE
DHL Express Formats are not up to date

### ISSUE THREAD

**Issue by hoppities** [jkeen/tracking_number_data#81]
Hi!

https://www.dhl.com/us-en/home/tracking/id-labels.html

I was looking at this package, and I noticed that the DHL formats do not support DHL's documentation.

**Comment by jkeen** [comment]
Thanks for this resource! Stuff like this from the source is always a huge help in figuring out what's what. I'll be making some updates

**Comment by jkeen** [comment]
Updated in 1.4.0

**Comment by hoppities** [comment]
Thank you for your work!
