### ISSUE TITLE
generator for mod_37_36

### ISSUE THREAD

**Issue by funwithbots** [jkeen/tracking_number_data#89]
DPD has `mod_37_36` as the validation algorithm for the check digit. It's not referenced in https://github.com/jkeen/tracking_number_data/blob/main/CHECKSUM_ALGORITHMS.md Do you have a source for how it is generated?

**Comment by jkeen** [comment]
Looks like I missed that one! Thanks for letting me know. 

I updated that doc with current examples from the ruby implementation of tracking_number
